import React, { useState, useEffect } from 'react';
import { useAuthStore } from '../store/authStore';
import { useGenStore } from '../store/genStore';
import { localDb } from '../utils/localDb';
import { Image as ImageIcon, Loader2, Download, Trash2, Edit, Share2, Send, History, X, MessageCircle, ExternalLink, Paperclip, Mic, MicOff } from 'lucide-react';
import { GoogleGenAI } from '@google/genai';
import { autoRetry } from '../utils/autoRetry';
import Logo from '../components/Logo';

const ALLOWED_TYPES = [
  'image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif',
  'text/plain', 'text/markdown', 'application/pdf', 'text/csv', 'text/html', 'text/xml',
  'application/rtf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'audio/mpeg', 'audio/mp3', 'audio/wav', 'audio/ogg',
  'video/mp4', 'video/mpeg', 'video/quicktime'
];

interface GeneratedImage {
  id: number;
  prompt: string;
  image_url: string;
  created_at: string;
  isEdit?: boolean;
}

export default function ImageGen() {
  const { token } = useAuthStore();
  const {
    imagePrompt: prompt,
    isImageGenerating: isLoading,
    imageError: error,
    setImageState,
    generateImage,
    editImage
  } = useGenStore();

  const setPrompt = (p: string) => setImageState({ imagePrompt: p });

  const [images, setImages] = useState<GeneratedImage[]>([]);
  const [confirmDeleteId, setConfirmDeleteId] = useState<number | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [imageToEdit, setImageToEdit] = useState<string | null>(null);
  const [isHistoryOpen, setIsHistoryOpen] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [isListening, setIsListening] = useState(false);
  const [interimTranscript, setInterimTranscript] = useState('');
  const [recordingTime, setRecordingTime] = useState(0);
  const [isExpanded, setIsExpanded] = useState(false);
  const textareaRef = React.useRef<HTMLTextAreaElement>(null);
  const fileInputRef = React.useRef<HTMLInputElement>(null);
  const scrollRef = React.useRef<HTMLDivElement>(null);

  useEffect(() => {
    fetchImages();
  }, []);

  useEffect(() => {
    if (scrollRef.current && !isHistoryOpen) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [images, isHistoryOpen]);

  const fetchImages = async () => {
    const allImages = localDb.getImages();
    setImages(allImages);
  };

  const handleShare = async (img: GeneratedImage) => {
    const shareText = `Check out this image generated by Tahir GPT: ${img.prompt}`;
    
    if (navigator.share) {
      try {
        const response = await fetch(img.image_url);
        const blob = await response.blob();
        const file = new File([blob], 'tahir-ai-image.png', { type: 'image/png' });
        
        if (navigator.canShare && navigator.canShare({ files: [file] })) {
          await navigator.share({
            title: 'Tahir GPT Image',
            text: shareText,
            files: [file]
          });
          return;
        }
      } catch (err) {
        console.error('Share error:', err);
      }
    }
    
    // Fallback to WhatsApp
    const waUrl = `https://wa.me/?text=${encodeURIComponent(shareText + ' ' + img.image_url)}`;
    window.open(waUrl, '_blank');
  };

  const deleteImage = async (id: number, e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    
    if (confirmDeleteId !== id) {
      setConfirmDeleteId(id);
      setTimeout(() => setConfirmDeleteId(null), 3000);
      return;
    }
    
    try {
      localDb.deleteImage(id);
      setImages(prev => prev.filter(img => img.id !== id));
      setConfirmDeleteId(null);
    } catch (err) {
      console.error('Delete error:', err);
      setImageState({ imageError: 'Network error while deleting image' });
    }
  };

  const downloadImage = async (imageUrl: string, filename: string) => {
    try {
      // For data URLs
      if (imageUrl.startsWith('data:')) {
        const link = document.createElement('a');
        link.href = imageUrl;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        return;
      }

      // For regular URLs
      const response = await fetch(imageUrl, { mode: 'cors' });
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      
      setTimeout(() => {
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
      }, 100);
    } catch (err) {
      console.error('Download error:', err);
      // Fallback: Open in new window for manual save
      const newTab = window.open();
      if (newTab) {
        newTab.document.write(`<img src="${imageUrl}" style="max-width:100%">`);
      } else {
        alert("Please allow popups to download images, or long-press the image to save.");
      }
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.size > 10 * 1024 * 1024) {
        setImageState({ imageError: 'File size must be less than 10MB' });
        return;
      }
      setSelectedFile(file);
    }
  };

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if ((!prompt.trim() && !selectedFile) || isLoading) return;

    let fileContext: { data: string, mimeType: string } | undefined;
    if (selectedFile) {
      try {
        const reader = new FileReader();
        const base64Promise = new Promise<string>((resolve) => {
          reader.onload = () => {
            const base64 = (reader.result as string).split(',')[1];
            resolve(base64);
          };
        });
        reader.readAsDataURL(selectedFile);
        const base64 = await base64Promise;
        fileContext = { data: base64, mimeType: selectedFile.type };
      } catch (err) {
        console.error('File read error:', err);
      }
    }

    if (isEditing && imageToEdit) {
      await editImage(prompt, imageToEdit);
      setIsEditing(false);
      setImageToEdit(null);
    } else {
      await generateImage(prompt, fileContext);
    }
    setSelectedFile(null);
    fetchImages();
  };

  const startEditing = (img: GeneratedImage) => {
    setIsEditing(true);
    setImageToEdit(img.image_url);
    setPrompt(`Edit this image: `);
    setIsHistoryOpen(false);
    setTimeout(() => {
      if (scrollRef.current) {
        scrollRef.current.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
      }
      textareaRef.current?.focus();
    }, 100);
  };

  const toggleListening = () => {
    if (isListening) {
      setIsListening(false);
      setRecordingTime(0);
      return;
    }

    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      setImageState({ imageError: 'Voice input is not supported in this browser.' });
      return;
    }

    const recognition = new SpeechRecognition();
    recognition.continuous = true;
    recognition.interimResults = true;
    recognition.lang = 'en-US';

    recognition.onstart = () => {
      setIsListening(true);
      setRecordingTime(0);
    };

    recognition.onresult = (event: any) => {
      let interim = '';
      for (let i = event.resultIndex; i < event.results.length; ++i) {
        if (event.results[i].isFinal) {
          const transcript = event.results[i][0].transcript;
          setImageState({ imagePrompt: prompt + transcript });
          setInterimTranscript('');
        } else {
          interim += event.results[i][0].transcript;
        }
      }
      setInterimTranscript(interim);
    };

    recognition.onerror = (event: any) => {
      console.error('Speech recognition error:', event.error);
      setIsListening(false);
    };

    recognition.onend = () => {
      setIsListening(false);
      setInterimTranscript('');
    };

    recognition.start();
  };

  useEffect(() => {
    let interval: any;
    if (isListening) {
      interval = setInterval(() => {
        setRecordingTime(prev => prev + 1);
      }, 1000);
    } else {
      clearInterval(interval);
    }
    return () => clearInterval(interval);
  }, [isListening]);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  return (
    <div className="flex h-full max-w-6xl mx-auto relative overflow-hidden bg-white dark:bg-black">
      {/* History Sidebar */}
      <div className={`fixed inset-y-0 left-0 z-40 w-72 bg-white dark:bg-zinc-900 border-r border-zinc-100 dark:border-zinc-800 transform transition-transform duration-300 ease-in-out lg:relative lg:translate-x-0 ${isHistoryOpen ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="flex flex-col h-full">
          <div className="p-6 border-b border-zinc-100 dark:border-zinc-800 flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <History className="w-5 h-5 text-zinc-400" />
              <h2 className="text-sm font-black uppercase tracking-widest text-zinc-900 dark:text-zinc-100">History</h2>
            </div>
            <button onClick={() => setIsHistoryOpen(false)} className="lg:hidden p-2 text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100">
              <X className="w-5 h-5" />
            </button>
          </div>
          <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
            {images.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-full opacity-30 text-center">
                <ImageIcon className="w-10 h-10 mb-2" />
                <p className="text-[10px] font-bold uppercase tracking-widest">No history</p>
              </div>
            ) : (
              images.slice().reverse().map((img) => (
                <div 
                  key={img.id} 
                  className="group relative aspect-square rounded-xl overflow-hidden border border-zinc-100 dark:border-zinc-800 cursor-pointer hover:ring-2 hover:ring-zinc-500 transition-all"
                  onClick={() => {
                    const el = document.getElementById(`img-${img.id}`);
                    if (el) el.scrollIntoView({ behavior: 'smooth' });
                    setIsHistoryOpen(false);
                  }}
                >
                  <img src={img.image_url} className="w-full h-full object-cover" alt="History" referrerPolicy="no-referrer" />
                  <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center space-x-2">
                    <button onClick={(e) => { e.stopPropagation(); startEditing(img); }} className="p-2 bg-white text-zinc-900 rounded-lg"><Edit className="w-3 h-3" /></button>
                    <button onClick={(e) => { e.stopPropagation(); deleteImage(img.id, e); }} className="p-2 bg-red-500 text-white rounded-lg"><Trash2 className="w-3 h-3" /></button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex flex-col h-full relative min-w-0">
        <div className="flex items-center justify-between px-6 py-4 border-b border-zinc-100 dark:border-zinc-800 bg-white/80 dark:bg-zinc-900/80 backdrop-blur-xl sticky top-0 z-20">
          <div className="flex items-center space-x-4">
            <button onClick={() => setIsHistoryOpen(true)} className="p-2 text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800 rounded-xl transition-colors">
              <History className="w-5 h-5" />
            </button>
            <div className="flex items-center space-x-2">
              <Logo className="w-8 h-8" />
              <h1 className="text-lg font-black text-zinc-900 dark:text-zinc-100 tracking-tight hidden sm:block">Image Studio</h1>
            </div>
          </div>
          <div className="flex items-center space-x-2">
            <span className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest bg-emerald-50 dark:bg-emerald-900/20 px-2 py-1 rounded-md">Live</span>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-4 md:p-8 space-y-8 custom-scrollbar bg-zinc-50/30 dark:bg-black/20">
          {images.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-center space-y-6">
              <div className="w-24 h-24 bg-white dark:bg-zinc-900 rounded-[2rem] shadow-2xl flex items-center justify-center rotate-3">
                <ImageIcon className="w-10 h-10 text-zinc-300" />
              </div>
              <div className="space-y-2">
                <h2 className="text-2xl font-black text-zinc-900 dark:text-zinc-100 tracking-tight">Create Anything</h2>
                <p className="text-sm text-zinc-500 max-w-xs mx-auto font-medium leading-relaxed">Describe your vision and watch it come to life in seconds.</p>
              </div>
            </div>
          ) : (
            <div className="space-y-16 max-w-3xl mx-auto">
              {images.map((img, index) => (
                <div 
                  key={img.id} 
                  id={`img-${img.id}`}
                  className="flex flex-col space-y-4 animate-in fade-in slide-in-from-bottom-8 duration-700"
                >
                  <div className="flex items-start space-x-4">
                    <div className="w-8 h-8 rounded-full bg-zinc-900 text-white dark:bg-white dark:text-zinc-900 flex items-center justify-center text-[10px] font-black shadow-lg">
                      {index + 1}
                    </div>
                    <div className="flex-1 space-y-6">
                      <div className="bg-white dark:bg-zinc-900 p-5 rounded-2xl border border-zinc-100 dark:border-zinc-800 shadow-sm inline-block max-w-full">
                        <p className="text-sm font-bold text-zinc-800 dark:text-zinc-200 leading-relaxed">
                          {img.prompt}
                        </p>
                      </div>
                      
                      <div className="relative group">
                        <div className="rounded-3xl overflow-hidden border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-2xl transition-transform duration-500 group-hover:scale-[1.01]">
                          <img
                            src={img.image_url}
                            alt={img.prompt}
                            className="w-full h-auto object-cover"
                            loading="lazy"
                            referrerPolicy="no-referrer"
                          />
                        </div>
                        
                        <div className="mt-4 flex flex-wrap items-center gap-2">
                          <button
                            onClick={() => startEditing(img)}
                            className="flex items-center space-x-2 px-4 py-2.5 bg-white dark:bg-zinc-900 text-zinc-900 dark:text-white rounded-xl border border-zinc-200 dark:border-zinc-800 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-all shadow-sm active:scale-95 text-xs font-bold"
                          >
                            <Edit className="w-4 h-4" />
                            <span>Edit</span>
                          </button>
                          <button
                            onClick={() => downloadImage(img.image_url, `tahir-ai-${img.id}.jpg`)}
                            className="flex items-center space-x-2 px-4 py-2.5 bg-white dark:bg-zinc-900 text-zinc-900 dark:text-white rounded-xl border border-zinc-200 dark:border-zinc-800 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-all shadow-sm active:scale-95 text-xs font-bold"
                          >
                            <Download className="w-4 h-4" />
                            <span>Save to Gallery</span>
                          </button>
                          <button
                            onClick={() => handleShare(img)}
                            className="flex items-center space-x-2 px-4 py-2.5 bg-emerald-500 text-white rounded-xl hover:bg-emerald-600 transition-all shadow-md active:scale-95 text-xs font-bold"
                          >
                            <MessageCircle className="w-4 h-4" />
                            <span>WhatsApp</span>
                          </button>
                          <button
                            onClick={() => {
                              const url = `https://t.me/share/url?url=${encodeURIComponent(img.image_url)}&text=${encodeURIComponent(img.prompt)}`;
                              window.open(url, '_blank');
                            }}
                            className="flex items-center space-x-2 px-4 py-2.5 bg-sky-500 text-white rounded-xl hover:bg-sky-600 transition-all shadow-md active:scale-95 text-xs font-bold"
                          >
                            <ExternalLink className="w-4 h-4" />
                            <span>Telegram</span>
                          </button>
                          <button
                            onClick={(e) => deleteImage(img.id, e)}
                            className={`flex items-center space-x-2 px-4 py-2.5 rounded-xl transition-all shadow-sm active:scale-95 text-xs font-bold border ${confirmDeleteId === img.id ? 'bg-red-500 text-white border-red-500' : 'bg-white dark:bg-zinc-900 text-red-500 border-zinc-200 dark:border-zinc-800 hover:bg-red-50'}`}
                          >
                            <Trash2 className="w-4 h-4" />
                            <span>{confirmDeleteId === img.id ? 'Confirm' : 'Delete'}</span>
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
          <div className="h-20 md:h-10" />
        </div>

        <div className="fixed bottom-0 left-0 right-0 md:sticky md:bottom-0 p-4 md:p-6 bg-white/95 dark:bg-black/95 backdrop-blur-xl border-t border-gray-200 dark:border-zinc-800 z-30 shadow-[0_-8px_30px_rgba(0,0,0,0.04)] dark:shadow-[0_-8px_30px_rgba(0,0,0,0.3)]">
          <div className="max-w-full mx-auto w-full">
            {selectedFile && (
              <div className="mb-3 flex items-center bg-zinc-50 dark:bg-zinc-800/50 p-2 px-3 rounded-xl inline-flex border border-gray-200 dark:border-zinc-700 backdrop-blur-sm">
                <Paperclip className="w-3 h-3 text-zinc-600 mr-2" />
                <span className="text-xs font-bold text-zinc-600 dark:text-zinc-400 truncate max-w-[150px]">{selectedFile.name}</span>
                <button 
                  type="button" 
                  onClick={() => setSelectedFile(null)}
                  className="ml-2 p-1 text-gray-400 hover:text-red-500 transition-colors"
                >
                  <X className="w-3 h-3" />
                </button>
              </div>
            )}
            
            <form onSubmit={handleGenerate} className="relative flex items-center w-full gap-3">
              <input
                type="file"
                ref={fileInputRef}
                onChange={handleFileChange}
                className="hidden"
                accept={ALLOWED_TYPES.join(',')}
              />
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                className="p-2.5 text-gray-400 hover:text-zinc-600 dark:hover:text-zinc-400 transition-all active:scale-90 shrink-0"
                title="Attach File"
              >
                <Paperclip className="w-6 h-6" />
              </button>

              <div className="relative flex-1">
                {isEditing && imageToEdit && (
                  <div className="absolute -top-16 left-0 right-0 flex items-center justify-between p-3 bg-zinc-900 text-white rounded-t-2xl text-[10px] font-black uppercase tracking-widest animate-in slide-in-from-bottom-4">
                    <div className="flex items-center space-x-2">
                      <Edit className="w-3 h-3 text-emerald-400" />
                      <span>Editing Mode Active</span>
                    </div>
                    <button 
                      type="button" 
                      onClick={() => { setIsEditing(false); setImageToEdit(null); setPrompt(''); }}
                      className="text-red-400 hover:text-red-300 flex items-center space-x-1"
                    >
                      <X className="w-3 h-3" />
                      <span>Cancel</span>
                    </button>
                  </div>
                )}
                <textarea
                  ref={textareaRef}
                  rows={1}
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder={isListening ? (interimTranscript || "Listening...") : (isEditing ? "Describe changes..." : "Describe image...")}
                  className={`w-full pl-4 pr-10 py-3 bg-gray-50 dark:bg-zinc-800/50 border border-gray-200 dark:border-zinc-800 rounded-2xl focus:outline-none focus:ring-2 focus:ring-zinc-500 focus:bg-white dark:focus:bg-zinc-800 transition-all text-base resize-none overflow-y-auto break-words custom-scrollbar ${isListening ? 'ring-2 ring-red-500 animate-pulse' : ''} ${isEditing ? 'rounded-t-none' : ''}`}
                  disabled={isLoading}
                />

                <button
                  type="button"
                  onClick={() => setIsExpanded(!isExpanded)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 p-1 text-black dark:text-white transition-colors z-10"
                  title={isExpanded ? "Collapse" : "Expand"}
                >
                  <span className="text-[10px] font-black tracking-tighter hover:scale-110 transition-transform inline-block">{"<>"}</span>
                </button>

                {isListening && (
                  <div className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center space-x-2 bg-white dark:bg-zinc-900 px-2 py-1 rounded-lg border border-red-100 dark:border-red-900/30 z-10">
                    <div className="w-1.5 h-1.5 bg-red-500 rounded-full animate-ping" />
                    <span className="text-[9px] font-black text-red-500">{formatTime(recordingTime)}</span>
                  </div>
                )}
              </div>

              <div className="flex items-center shrink-0 gap-2">
                <button
                  type="button"
                  onClick={toggleListening}
                  className={`p-2.5 rounded-xl transition-all ${isListening ? 'text-red-500 bg-red-50 dark:bg-red-900/20' : 'text-gray-400 hover:text-zinc-600 dark:hover:text-zinc-400'}`}
                  title={isListening ? "Stop Listening" : "Start Voice Input"}
                >
                  {isListening ? <MicOff className="w-6 h-6" /> : <Mic className="w-6 h-6" />}
                </button>
                
                <button
                  type="submit"
                  disabled={(!prompt.trim() && !selectedFile) || isLoading}
                  className="p-2.5 text-white bg-zinc-900 dark:bg-zinc-100 dark:text-zinc-900 rounded-xl hover:opacity-90 disabled:opacity-30 disabled:cursor-not-allowed transition-all shadow-lg"
                >
                  {isLoading ? <Loader2 className="w-6 h-6 animate-spin" /> : <Send className="w-6 h-6" />}
                </button>
              </div>
            </form>
            {error && <p className="text-[10px] text-red-500 font-bold text-center mt-2">{error}</p>}
          </div>
        </div>
      </div>
    </div>
  );
}
