import React from 'react';
import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-zinc-900 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-white dark:bg-zinc-800 p-8 rounded-2xl shadow-xl border border-gray-100 dark:border-zinc-700">
        <h1 className="text-3xl font-black text-gray-900 dark:text-gray-100 mb-8 tracking-tight">Terms and Conditions</h1>
        
        <div className="prose prose-zinc dark:prose-invert max-w-none space-y-6 text-gray-700 dark:text-gray-300">
          <p className="italic">Last Updated: March 4, 2026</p>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-3">1. Acceptance of Terms</h2>
            <p>By creating an account or using Tahir GPT, you agree to these Terms and Conditions. These terms govern your use of our AI-powered platform, including chat, image generation, and web development tools.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-3">2. Service Description</h2>
            <p>Tahir GPT provides an advanced AI interface for productivity and creativity. While we strive for 100% accuracy, AI-generated content may occasionally contain errors. Users are encouraged to verify critical information.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-3">3. User Responsibilities</h2>
            <p>You are responsible for the content you generate and share. You agree not to use Tahir GPT for:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Generating harmful, illegal, or discriminatory content.</li>
              <li>Impersonating others or violating intellectual property rights.</li>
              <li>Attempting to reverse-engineer or disrupt the service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-3">4. Intellectual Property</h2>
            <p>Content generated by Tahir GPT is generally owned by the user, subject to the terms of the underlying AI models (e.g., Google Gemini). The Tahir GPT brand, logo, and platform code remain the exclusive property of Tahir Manj.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-3">5. Limitation of Liability</h2>
            <p>Tahir GPT is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service or reliance on AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-3">6. Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these terms or engage in abusive behavior towards the platform or other users.</p>
          </section>
        </div>

        <div className="mt-10 pt-6 border-t border-gray-100 dark:border-zinc-700">
          <Link to="/login" className="text-indigo-600 hover:text-indigo-500 font-bold">Back to Login</Link>
        </div>
      </div>
    </div>
  );
}
